language: ruby
rvm:
  - 1.9.3

env:
  - DB=postgresql

before_script:
  - psql -c 'create database slurryhub_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec cucumber

